# Generated by Django 4.0.1 on 2022-05-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookseites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seites', models.CharField(max_length=10)),
                ('name_seites1', models.CharField(blank=True, max_length=100, null=True)),
                ('name_seites', models.CharField(blank=True, max_length=100, null=True)),
                ('name_step', models.CharField(blank=True, max_length=1, null=True)),
                ('image_seites', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['image_seites'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_art', models.CharField(max_length=30)),
                ('reg_f_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_s_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_numbers', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_seites', models.ManyToManyField(to='bookland.Bookseites')),
            ],
            options={
                'ordering': ['reg_art', 'reg_f_name'],
            },
        ),
    ]
