# Generated by Django 4.0.1 on 2022-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0002_bookseites_eng_bookseites_content_seite_register_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('ukr', models.TextField(blank=True, null=True)),
                ('eng', models.TextField(blank=True, null=True)),
                ('ita', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
