# Generated by Django 4.0.1 on 2022-06-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0003_text_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ukr', models.CharField(blank=True, max_length=50, null=True)),
                ('eng', models.CharField(blank=True, max_length=50, null=True)),
                ('ita', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
