# Generated by Django 4.0.1 on 2022-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0005_register_object_register_eng_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Object',
            new_name='Object_typ',
        ),
        migrations.AlterModelOptions(
            name='object_typ',
            options={'ordering': ['ukr']},
        ),
        migrations.RemoveField(
            model_name='register',
            name='object',
        ),
        migrations.RemoveField(
            model_name='register_eng',
            name='object',
        ),
        migrations.AddField(
            model_name='register',
            name='object_typ',
            field=models.ManyToManyField(to='bookland.Object_typ'),
        ),
        migrations.AddField(
            model_name='register_eng',
            name='object_typ',
            field=models.ManyToManyField(to='bookland.Object_typ'),
        ),
    ]
