# Generated by Django 4.0.1 on 2022-06-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0007_bookseites_content_eng_bookseites_name_eng_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookseites_eng',
        ),
    ]
