# Generated by Django 4.0.1 on 2022-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0009_register_reg_f_eng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookseites_eng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seites', models.CharField(max_length=10)),
                ('name_seites1', models.CharField(blank=True, max_length=100, null=True)),
                ('name_seites', models.CharField(blank=True, max_length=100, null=True)),
                ('name_step', models.CharField(blank=True, max_length=1, null=True)),
                ('image_seites', models.CharField(blank=True, max_length=30, null=True)),
                ('content_seite', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['image_seites'],
            },
        ),
    ]
