# Generated by Django 4.0.1 on 2022-06-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookland', '0013_rename_control_bookseites_contr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookseites',
            name='control',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
